# ==============================================================================
# SCRIPT: Landscape composition and configuration as drivers of 
#         Effective Habitat Area (EHA) of threatened mammals
# TARGET JOURNAL: Landscape Ecology
# AUTHOR: Maria Eduarda Nacif
# REVISED VERSION: May 2026 (v3 - Color palettes standardized)
#
# REVISION NOTES (v3 - COLOR PALETTE REVISION):
# (ix)  All color palettes standardized to Springer-friendly, colorblind-safe 
#       specifications (Okabe-Ito & custom derivatives).
# (x)   Genus palette for NMDS and response curves: 8 colors, ecologically motivated.
# (xi)  Locomotion palette: 3 distinct colors aligned with Bloco 8.
# (xii) Diet palette: 4 colors aligned with Bloco 8.
# (xiii)Removed hard-coded color switches; centralized in color definition section.
#
# REVISION NOTES (v2):
# (i)   Response variable renamed from UA_Area_ha to EHA_ha (Effective Habitat 
#       Area, IUCN-aligned; see Greco et al. 2025).
# (ii)  Permutation count standardized to 9,999 across all randomization-based 
#       tests (envfit, adonis2, pairwise.adonis, betadisper).
# (iii) set.seed() asserted immediately before every stochastic procedure 
#       (NMDS, permutation tests, DHARMa simulations) for full reproducibility.
# (iv)  Largest Patch Index (LPI) excluded from GLMM modelling due to extreme 
#       collinearity with PLAND (VIF = 53.12 and 48.79, respectively); LPI was 
#       retained in the multivariate envfit because its ecological signature 
#       (dominance of a single core remnant) is structurally distinct from the 
#       proportional cover captured by PLAND.
# (v)   DHARMa residual diagnostics (dispersion, uniformity, outliers) now 
#       exported as a structured supplementary table for auditability.
# (vi)  The constant 0.001 added to zero-valued EHA observations is documented 
#       and a sensitivity analysis is provided (alternatives: 0.01, 0.1).
# (vii) Working directory referenced via a single configurable variable; users 
#       are encouraged to adopt the here::here() convention when porting the 
#       script across systems.
# (viii) sessionInfo() reported at the end to log package versions.
#
# ANALYTICAL FRAMEWORK:
# 1. Collinearity diagnostics via Pearson correlation and Variance Inflation 
#    Factor (VIF; threshold = 5).
# 2. Multivariate analysis of community structure (NMDS, betadisper, PERMANOVA, 
#    pairwise PERMANOVA with FDR correction).
# 3. Univariate Generalized Linear Mixed Models (GLMM, Gamma family, log link) 
#    with species as a random intercept, falling back to GLM for taxa with a 
#    single species.
# 4. Multimodel inference based on AICc (delta < 2) with model averaging.
# 5. Residual diagnostics via DHARMa simulation framework.
# ==============================================================================

# ==============================================================================
# 1. ENVIRONMENT SETUP & COLOR PALETTES
# ==============================================================================
suppressPackageStartupMessages({
  library(here)        # reproducible paths
  library(vegan)       # multivariate ecology (NMDS, PERMANOVA, envfit)
  library(tidyverse)   # data wrangling and plotting
  library(ggtext)      # rich text in ggplot
  library(scales)      # axis formatting
  library(cluster)     # multivariate utilities
  library(patchwork)   # multi-panel composition
  library(MuMIn)       # multimodel inference (dredge, model.avg)
  library(DHARMa)      # residual diagnostics
  library(emmeans)     # marginal means and response curves
  library(corrplot)    # correlation plots
  library(lme4)        # mixed-effects models
  library(car)         # VIF
})

# Global reproducibility seed; replicated locally before each stochastic call.
GLOBAL_SEED <- 123

# Permutation count for randomization-based tests (Anderson, 2017).
N_PERM <- 9999

# Configurable paths (using here:: relative to project root).
# Project root is wherever ANALISES_TCC.Rproj lives (D:/Duda_Nacif_TCC).
# data_path  = where input CSVs live (Dados/Processados)
# output_path = where figures and tables generated by this script are saved
library(here)
data_path   <- here("Dados", "Processados")
output_path <- here("Outputs", "Manuscrito")

# ==============================================================================
# 1.1 COLOR PALETTES (SPRINGER-FRIENDLY, COLORBLIND-SAFE)
# ==============================================================================
# All palettes designed for publication in Springer journals, accessibility,
# and ecological intuition. Tested with colorblind simulators.

# PALETTE 1: GENUS (8 species) - Okabe-Ito derivative
colors_genus <- c(
  "Puma"         = "#D55E00",    # Orange-red (carnivore, active hunter)
  "Alouatta"     = "#009E73",    # Green (foliage-dependent)
  "Mazama"       = "#CC79A7",    # Rose (deer, intermediate)
  "Brachyteles"  = "#E69F00",    # Orange (canopy specialist)
  "Tayassu"      = "#0072B2",    # Blue (gregarious, terrestrial)
  "Myrmecophaga" = "#F0E442",    # Yellow (open-habitat affinity)
  "Leopardus"    = "#56B4E9",    # Light blue (small felid, cryptic)
  "Bradypus"     = "#999999"     # Gray (arboreal but isolated)
)

# PALETTE 2: LOCOMOTION (3 categories)
colors_locomotion <- c(
  "Arboreal"     = "#2E7D32",    # Dark green (arboreal habitat)
  "Scansorial"   = "#D2B48C",    # Tan/Bege (intermediate)
  "Terrestrial"  = "#1565C0"     # Dark blue (ground-dwelling)
)

# PALETTE 3: DIET (4 categories)
colors_diet <- c(
  "Ca"      = "#D32F2F",         # Red (Carnivore)
  "Fr/Fo"   = "#388E3C",         # Green (Frugivore/Folivore)
  "Hb/Fr"   = "#F57C00",         # Orange (Herbivore/Frugivore)
  "Fr/On"   = "#7B1FA2"          # Purple (Frugivore/Omnivore)
)

# Dictionary for diet labels
diet_labels_dict <- c(
  "Ca"    = "Carnivore",
  "Fr/Fo" = "Frugivore/Folivore",
  "Hb/Fr" = "Herbivore/Frugivore",
  "Fr/On" = "Frugivore/Omnivore"
)

# ==============================================================================
# 2. ANALYTICAL FUNCTIONS
# ==============================================================================

# A) High-resolution plot export (TIFF, 600 dpi, LZW compression)
save_publication_plot <- function(plot_obj, file_name, width_mm = 174, height_mm = 200) {
  if (!is.null(plot_obj)) {
    ggsave(filename = file_name, plot = plot_obj, path = output_path,
           width = width_mm, height = height_mm, units = "mm",
           dpi = 600, device = "tiff", compression = "lzw", bg = "white")
    message(sprintf("Plot exported: %s", file_name))
  }
}

# B) Pairwise PERMANOVA with FDR correction
# Permutations standardized to N_PERM (9,999); set.seed asserted at each call.
pairwise.adonis <- function(x, factors, sim.method = 'euclidean',
                            p.adjust.m = 'fdr', n_perm = N_PERM, seed = GLOBAL_SEED) {
  co <- combn(unique(as.character(factors)), 2)
  pairs <- character(0); F.Model <- numeric(0); R2 <- numeric(0); p.value <- numeric(0)
  
  for (elem in seq_len(ncol(co))) {
    sub_idx <- factors %in% c(co[1, elem], co[2, elem])
    x1 <- vegdist(x[sub_idx, ], method = sim.method)
    
    set.seed(seed)  # reproducibility within the loop
    ad <- adonis2(x1 ~ factors[sub_idx], permutations = n_perm)
    
    pairs   <- c(pairs, paste(co[1, elem], 'vs', co[2, elem]))
    F.Model <- c(F.Model, ad$F[1])
    R2      <- c(R2, ad$R2[1])
    p.value <- c(p.value, ad$`Pr(>F)`[1])
  }
  
  p.adjusted <- p.adjust(p.value, method = p.adjust.m)
  
  data.frame(
    pairs = pairs,
    F.Model = round(F.Model, 4),
    R2 = round(R2, 4),
    p.value = round(p.value, 4),
    p.adjusted = round(p.adjusted, 4),
    sig = ifelse(p.adjusted < 0.05, '*', '')
  )
}

# C) GLMM + GLM model selection
# Max terms logic: 2 when n < 15; otherwise floor(n/10) capped at 5.
# Exclusion rules prevent structural collinearity in the same formula.
run_model_selection <- function(target_name, filter_col, full_data) {
  
  data_subset <- full_data %>% filter(.data[[filter_col]] == target_name)
  
  # Constant addition for Gamma compatibility (see header note)
  data_subset$EHA_ha <- ifelse(data_subset$EHA_ha == 0, 0.001, data_subset$EHA_ha)
  
  n <- nrow(data_subset)
  if (n < 5) return(NULL)
  
  n_spp <- length(unique(data_subset$SPECIES))
  # Restore na.action on function exit to avoid persistent global side effects
  old_na_action <- getOption("na.action")
  on.exit(options(na.action = old_na_action), add = TRUE)
  options(na.action = "na.fail")
  
  # Exclusion rule preventing structurally collinear metrics in the same formula
  subset_rule <- expression(!(PD_Forest && PLAND_Forest) &
                              !(PROX_MN_Forest && PD_Forest) &
                              !(PROX_MN_Forest && PLAND_Forest) &
                              !(Mean_AREA_Forest_ha && Mean_ENN_Forest_m) &
                              !(ED_Forest && PD_Forest))
  
  # Dynamic complexity ceiling
  max_terms <- if (n < 15) 2 else min(5, max(2, floor(n / 10)))
  
  global_model <- NULL
  
  # GLMM for functionally grouped subsets (>1 species)
  if (n_spp > 1) {
    global_model <- tryCatch({
      glmer(EHA_ha ~ PLAND_Forest + NP_Forest + PD_Forest +
              Mean_FRAC_Forest + PROX_MN_Forest + Mean_AREA_Forest_ha + ED_Forest +
              Mean_Elevation_m + Mean_Pop_Density + Mean_ENN_Forest_m +
              (1 | SPECIES),
            data = data_subset, family = Gamma(link = "log"),
            control = glmerControl(optimizer = "bobyqa",
                                   optCtrl = list(maxfun = 100000)))
    }, error = function(e) {
      message(sprintf("   GLMM convergence failure for %s. Reverting to fixed-effects GLM.", target_name))
      NULL
    })
  }
  
  # Fixed-effects GLM as fallback or for single-species subsets
  if (is.null(global_model)) {
    global_model <- glm(EHA_ha ~ PLAND_Forest + NP_Forest + PD_Forest +
                          Mean_FRAC_Forest + PROX_MN_Forest + Mean_AREA_Forest_ha + ED_Forest +
                          Mean_Elevation_m + Mean_Pop_Density + Mean_ENN_Forest_m,
                        data = data_subset, family = Gamma(link = "log"))
  }
  
  dredge_table <- dredge(global_model, rank = "AICc",
                         m.lim = c(0, max_terms), trace = FALSE,
                         subset = subset_rule)
  
  # Model averaging across competitive models (delta AICc < 2)
  competitive_models <- get.models(dredge_table, subset = delta < 2)
  
  if (length(competitive_models) == 1) {
    final_model <- competitive_models[[1]]
    summary_msg <- "Single most parsimonious model retained."
  } else {
    final_model <- model.avg(competitive_models, fit = TRUE)
    summary_msg <- sprintf("%d competitive models retained for Model Averaging.",
                           length(competitive_models))
  }
  message(sprintf("   [%s] %s", target_name, summary_msg))
  
  list(table = dredge_table, model = final_model, n = n,
       n_competitive = length(competitive_models))
}

# D) Response curves visualization (with centralized color reference)
plot_response_curves <- function(model_obj, target_name, original_df,
                                 use_log_y = TRUE, line_color = "black",
                                 show_y_label = TRUE) {
  if (is.null(model_obj)) return(NULL)
  model <- model_obj$model
  
  if (inherits(model, "averaging")) {
    model <- get.models(model_obj$table, subset = 1)[[1]]
  }
  
  mod_data <- model.frame(model)
  
  if (inherits(model, "merMod")) {
    terms_raw <- attr(terms(formula(model, fixed.only = TRUE)), "term.labels")
  } else {
    terms_raw <- attr(terms(model), "term.labels")
  }
  
  simple_terms <- terms_raw[!grepl(":", terms_raw)]
  if (length(simple_terms) == 0) return(NULL)
  
  pred_list <- list()
  for (var in simple_terms) {
    min_z <- min(mod_data[[var]], na.rm = TRUE)
    max_z <- max(mod_data[[var]], na.rm = TRUE)
    seq_z <- seq(min_z, max_z, length.out = 100)
    
    emm <- as.data.frame(emmeans(model,
                                 specs = as.formula(paste("~", var)),
                                 at = setNames(list(seq_z), var),
                                 type = "response"))
    
    pred_col <- names(emm)[2]
    col_min  <- names(emm)[ncol(emm) - 1]
    col_max  <- names(emm)[ncol(emm)]
    
    media_orig <- mean(original_df[[var]], na.rm = TRUE)
    sd_orig    <- sd(original_df[[var]], na.rm = TRUE)
    
    pred_list[[var]] <- data.frame(
      Variable = var,
      x_real   = (emm[[var]] * sd_orig) + media_orig,
      y_pred   = emm[[pred_col]],
      y_min    = emm[[col_min]],
      y_max    = emm[[col_max]]
    )
  }
  
  df_preds <- bind_rows(pred_list)
  df_points <- original_df %>%
    filter(GENUS == target_name | LOCOMOTION == target_name | DIET == target_name) %>%
    select(any_of(c("EHA_ha", simple_terms))) %>%
    pivot_longer(cols = any_of(simple_terms), names_to = "Variable", values_to = "Valor_X") %>%
    mutate(EHA_ha = ifelse(EHA_ha == 0, 0.001, EHA_ha))
  
  nice_names <- c("PLAND_Forest"        = "Forest\nCover (%)",
                  "NP_Forest"           = "Number of\nPatches",
                  "PD_Forest"           = "Patch\nDensity",
                  "Mean_FRAC_Forest"    = "Fractal\nDimension",
                  "PROX_MN_Forest"      = "Proximity\nIndex",
                  "Mean_AREA_Forest_ha" = "Patch Area\n(ha)",
                  "ED_Forest"           = "Edge\nDensity",
                  "Mean_ENN_Forest_m"   = "Euclidean NN\nDistance (m)",
                  "Mean_Elevation_m"    = "Elevation\n(m)",
                  "Mean_Pop_Density"    = "Human\nPopulation")
  
  df_preds$Variable  <- dplyr::recode(df_preds$Variable, !!!nice_names)
  df_points$Variable <- dplyr::recode(df_points$Variable, !!!nice_names)
  
  p <- ggplot() +
    geom_point(data = df_points, aes(x = Valor_X, y = EHA_ha),
               alpha = 0.4, size = 2, color = "grey40") +
    geom_ribbon(data = df_preds, aes(x = x_real, ymin = y_min, ymax = y_max),
                fill = line_color, alpha = 0.2) +
    geom_line(data = df_preds, aes(x = x_real, y = y_pred),
              color = line_color, linewidth = 1) +
    facet_wrap(~Variable, scales = "free_x", strip.position = "top") +
    labs(x = NULL, y = "Effective Habitat Area (ha)",
         title = bquote(italic(.(target_name)) ~ "EHA Response Models")) +
    theme_classic(base_size = 10, base_family = "sans") +
    theme(strip.background = element_blank(),
          strip.text       = element_text(face = "bold", size = 9),
          plot.title       = element_text(face = "bold", size = 11, hjust = 0.5),
          axis.text.x      = element_text(size = 8.5),
          axis.title.y     = element_text(color = ifelse(show_y_label, "black", "transparent")))
  
  if (use_log_y) {
    p <- p + scale_y_log10(labels = label_comma())
  } else {
    p <- p + scale_y_continuous(labels = label_comma())
  }
  p + scale_x_continuous(labels = label_comma(), n.breaks = 4,
                         guide = guide_axis(n.dodge = 2))
}

# E) Extraction of variable importance (Akaike weights) and coefficient direction
# Direction is derived from the sign of model-averaged (or best-model) coefficients,
# not from Importance values, which are always non-negative.
extract_variable_importance <- function(results_list, group_name) {
  imp_list <- list()
  for (taxon in names(results_list)) {
    result     <- results_list[[taxon]]
    dredge_obj <- result$table
    model_obj  <- result$model
    if (!is.null(dredge_obj)) {
      imp   <- sw(dredge_obj)
      terms <- names(imp)

      coefs   <- tryCatch(coef(model_obj),
                          error = function(e) setNames(rep(NA_real_, length(terms)), terms))
      matched <- coefs[match(terms, names(coefs))]
      direction <- dplyr::case_when(
        !is.na(matched) & matched > 0 ~ "+",
        !is.na(matched) & matched < 0 ~ "-",
        TRUE                          ~ ""
      )

      imp_list[[taxon]] <- data.frame(
        Group      = group_name,
        Taxon      = taxon,
        Variable   = terms,
        Importance = as.numeric(imp),
        Direction  = direction,
        stringsAsFactors = FALSE
      )
    }
  }
  bind_rows(imp_list)
}

# ==============================================================================
# 3. DATA LOADING & PREPROCESSING
# ==============================================================================
message("\n[Initialization] Loading and formatting spatial datasets...")

data_raw_glm <- read_csv(file.path(data_path, "Data_Raw_GLM_NMDS_Final.csv"),
                         show_col_types = FALSE)

# Backwards compatibility: rename UA_Area_ha (legacy) to EHA_ha (current)
if ("UA_Area_ha" %in% names(data_raw_glm) && !"EHA_ha" %in% names(data_raw_glm)) {
  data_raw_glm <- data_raw_glm %>% rename(EHA_ha = UA_Area_ha)
  message("   Column UA_Area_ha renamed to EHA_ha.")
}

# Append legacy configuration metrics if present in an auxiliary file
legacy_path <- file.path(data_path, "UA_Variables_GLM.csv")
if (file.exists(legacy_path)) {
  dados_antigos <- read_csv(legacy_path, show_col_types = FALSE) %>%
    select(UA_ID, Mean_FRAC_Forest, Mean_ENN_Forest_m, Mean_AREA_Forest_ha) %>%
    distinct(UA_ID, .keep_all = TRUE)
  data_raw_glm <- data_raw_glm %>% left_join(dados_antigos, by = "UA_ID")
}

data_raw_glm <- data_raw_glm %>%
  mutate(across(c(ORDER, GENUS, SPECIES, DIET, LOCOMOTION, UA_ID), as.factor))

# Predictor pool. LPI_Forest is included for collinearity diagnostics and the 
# multivariate envfit, then excluded from GLMM modelling (see header note).
predictors <- c("PLAND_Forest", "NP_Forest", "PD_Forest", "Mean_FRAC_Forest",
                "Mean_ENN_Forest_m", "PROX_MN_Forest", "Mean_AREA_Forest_ha",
                "LPI_Forest", "ED_Forest", "Mean_Elevation_m", "Mean_Pop_Density")

data_z <- data_raw_glm
data_z[, predictors] <- scale(data_raw_glm[, predictors])

# ==============================================================================
# 3.1 COLLINEARITY DIAGNOSTICS (Pearson + VIF)
# ==============================================================================
message("\n[Diagnostics] Pearson correlation and Variance Inflation Factor...")

cor_matrix_glm <- cor(data_z[, predictors], use = "complete.obs", method = "pearson")

png(filename = file.path(output_path, "Collinearity_Correlation_GLM.png"),
    width = 2500, height = 2500, res = 300)
corrplot(cor_matrix_glm, method = "number", type = "upper", tl.col = "black",
         tl.srt = 45, title = "Landscape Predictors Correlation Matrix",
         mar = c(0, 0, 2, 0), number.cex = 0.7)
invisible(dev.off())

vif_model <- lm(EHA_ha ~ PLAND_Forest + NP_Forest + PD_Forest + Mean_FRAC_Forest +
                  Mean_ENN_Forest_m + PROX_MN_Forest + Mean_AREA_Forest_ha +
                  LPI_Forest + ED_Forest + Mean_Elevation_m + Mean_Pop_Density,
                data = data_z)

vif_values <- vif(vif_model)
df_vif <- data.frame(Variable = names(vif_values), VIF = round(vif_values, 2))
df_vif <- df_vif[order(-df_vif$VIF), ]
write.csv(df_vif, file.path(output_path, "Table_S_Collinearity_VIF.csv"),
          row.names = FALSE)
message("   VIF table exported.")

# ==============================================================================
# 4. MULTIVARIATE COMMUNITY ANALYSIS (NMDS, ENVFIT, PERMANOVA)
# ==============================================================================
message("\n[Analysis] Multivariate community structure...")

comp_vars <- data_raw_glm %>%
  select(CA_Forest, CA_Non_Vegetated, CA_Herbaceous, CA_Agropecuaria) %>%
  mutate(across(everything(), ~replace_na(.x, 0)))
names(comp_vars) <- c("Forest", "Non-Vegetated", "Herb/Shrub", "Agropecuaria")

cor_matrix_comp <- cor(comp_vars, use = "complete.obs", method = "spearman")
png(filename = file.path(output_path, "Correlation_Composition_NMDS.png"),
    width = 2000, height = 2000, res = 300)
corrplot(cor_matrix_comp, method = "number", type = "upper", tl.col = "black",
         tl.srt = 45, title = "Composition Variables Correlation",
         mar = c(0, 0, 2, 0))
invisible(dev.off())

LULC_sqrt <- sqrt(comp_vars)
LULC_dist <- vegdist(LULC_sqrt, method = "bray", na.rm = TRUE)

# NMDS ordination
set.seed(GLOBAL_SEED)
nmds_result <- metaMDS(LULC_dist, k = 2, trymax = 100, trace = FALSE)
message(sprintf("   NMDS stress: %.3f", nmds_result$stress))

# Environmental vector fitting (configuration metrics)
config_metrics <- data_raw_glm %>%
  select(Mean_FRAC_Forest, Mean_ENN_Forest_m, PROX_MN_Forest,
         Mean_AREA_Forest_ha, PLAND_Forest, PD_Forest, LPI_Forest, ED_Forest)

set.seed(GLOBAL_SEED)
envfit_result <- envfit(nmds_result, config_metrics,
                        permutations = N_PERM, na.rm = TRUE)

vetores_df <- as.data.frame(scores(envfit_result, display = "vectors"))
vetores_df$Metric  <- rownames(vetores_df)
vetores_df$R2      <- envfit_result$vectors$r
vetores_df$p_value <- envfit_result$vectors$pvals
write.csv(vetores_df,
          file.path(output_path, "Envfit_Configuration_Bray_Results.csv"),
          row.names = FALSE)

vetores_sig <- subset(vetores_df, p_value < 0.05)
vetores_sig$NMDS1  <- vetores_sig$NMDS1 * 1.2
vetores_sig$NMDS2  <- vetores_sig$NMDS2 * 1.2
vetores_sig$Metric <- gsub("_Forest", "", vetores_sig$Metric)

# NMDS plot with standardized genus colors
nmds_scores <- as.data.frame(scores(nmds_result, display = "sites"))
nmds_scores$Genus <- data_raw_glm$GENUS
hulls_genus <- nmds_scores %>%
  group_by(Genus) %>%
  slice(chull(NMDS1, NMDS2))

# Get color subset for only the genera present in the data
genera_present <- unique(data_raw_glm$GENUS)
colors_genus_subset <- colors_genus[names(colors_genus) %in% genera_present]

# Ensure we have the correct number of shapes
n_genera <- length(unique(hulls_genus$Genus))
shapes_genus <- 1:n_genera

plot_nmds_genus <- ggplot() +
  geom_polygon(data = hulls_genus,
               aes(x = NMDS1, y = NMDS2, fill = Genus, group = Genus),
               alpha = 0.3, color = "grey30") +
  geom_point(data = nmds_scores,
             aes(x = NMDS1, y = NMDS2, color = Genus, shape = Genus),
             size = 3, alpha = 0.8) +
  geom_segment(data = vetores_sig,
               aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")),
               color = "grey15", linewidth = 1, alpha = 0.8) +
  geom_text(data = vetores_sig,
            aes(x = NMDS1 * 1.1, y = NMDS2 * 1.1, label = Metric),
            color = "black", size = 3.5, fontface = "bold", family = "sans") +
  scale_fill_manual(values  = colors_genus_subset, na.value = "grey90") +
  scale_color_manual(values = colors_genus_subset, na.value = "grey50") +
  scale_shape_manual(values = shapes_genus) +
  labs(x = "NMDS 1", y = "NMDS 2",
       title = paste0("Landscape Ordination (Stress: ",
                      round(nmds_result$stress, 3), ")")) +
  theme_classic(base_size = 10, base_family = "sans") +
  theme(plot.title    = element_text(face = "bold", size = 11, hjust = 0.5),
        legend.title  = element_text(face = "bold", size = 10),
        legend.text   = element_text(size = 9))

save_publication_plot(plot_nmds_genus, "Figure2_Bray_NMDS_Genus_Final.tiff",
                      width_mm = 174, height_mm = 130)

# Multivariate dispersion (betadisper) and permutational ANOVA
set.seed(GLOBAL_SEED); disp_genus   <- betadisper(LULC_dist, data_raw_glm$GENUS)
set.seed(GLOBAL_SEED); disp_species <- betadisper(LULC_dist, data_raw_glm$SPECIES)
set.seed(GLOBAL_SEED); disp_diet    <- betadisper(LULC_dist, data_raw_glm$DIET)
set.seed(GLOBAL_SEED); disp_loc     <- betadisper(LULC_dist, data_raw_glm$LOCOMOTION)

df_beta_genus   <- as.data.frame(anova(disp_genus))   %>% mutate(Group = "Genus",      Source = rownames(.))
df_beta_species <- as.data.frame(anova(disp_species)) %>% mutate(Group = "Species",    Source = rownames(.))
df_beta_diet    <- as.data.frame(anova(disp_diet))    %>% mutate(Group = "Diet",       Source = rownames(.))
df_beta_loc     <- as.data.frame(anova(disp_loc))     %>% mutate(Group = "Locomotion", Source = rownames(.))

betadisper_results <- bind_rows(df_beta_genus, df_beta_species,
                                df_beta_diet, df_beta_loc) %>%
  select(Group, Source, everything())
write.csv(betadisper_results,
          file.path(output_path, "Table_S_Betadisper_Bray_Results.csv"),
          row.names = FALSE)

# ------------------------------------------------------------------------------
# Global PERMANOVA (adonis2) for all grouping variables
# Run before pairwise tests: pairwise decomposition is only interpretable when
# the global test is significant (Anderson & Walsh 2013, Ecology).
# ------------------------------------------------------------------------------
tidy_adonis <- function(adonis_obj, group_label) {
  row <- as.data.frame(adonis_obj)[1L, ]
  data.frame(
    Grouping = group_label,
    Df       = row$Df,
    SumOfSqs = round(row$SumOfSqs, 4),
    R2       = round(row$R2, 4),
    F_value  = round(row$F, 4),
    p_value  = row[["Pr(>F)"]]
  )
}

set.seed(GLOBAL_SEED)
adonis_genus   <- adonis2(LULC_dist ~ GENUS,      data = data_raw_glm, permutations = N_PERM)
set.seed(GLOBAL_SEED)
adonis_species <- adonis2(LULC_dist ~ SPECIES,    data = data_raw_glm, permutations = N_PERM)
set.seed(GLOBAL_SEED)
adonis_diet    <- adonis2(LULC_dist ~ DIET,       data = data_raw_glm, permutations = N_PERM)
set.seed(GLOBAL_SEED)
adonis_loc     <- adonis2(LULC_dist ~ LOCOMOTION, data = data_raw_glm, permutations = N_PERM)

permanova_global <- bind_rows(
  tidy_adonis(adonis_genus,   "Genus"),
  tidy_adonis(adonis_species, "Species"),
  tidy_adonis(adonis_diet,    "Diet"),
  tidy_adonis(adonis_loc,     "Locomotion")
)
write.csv(permanova_global,
          file.path(output_path, "Table_S_PERMANOVA_Global_Bray.csv"),
          row.names = FALSE)
message("   Global PERMANOVA table exported.")

# Pairwise PERMANOVA (FDR-adjusted) — Genus and Species
pairwise_genus <- pairwise.adonis(x = LULC_sqrt, factors = data_raw_glm$GENUS,
                                  sim.method = 'bray')
write.csv(pairwise_genus,
          file.path(output_path, "PERMANOVA_Bray_Pairwise_Genus.csv"),
          row.names = FALSE)

pairwise_sp <- pairwise.adonis(x = LULC_sqrt, factors = data_raw_glm$SPECIES,
                               sim.method = 'bray')
write.csv(pairwise_sp,
          file.path(output_path, "PERMANOVA_Bray_Pairwise_Species.csv"),
          row.names = FALSE)

# Pairwise PERMANOVA — Diet and Locomotion (complement global tests above)
# CAUTION: The global PERMANOVA for Diet (p ~ 0.08) and Locomotion (p ~ 0.30)
# did not reach alpha = 0.05. Pairwise decompositions are therefore exploratory
# only and should not be presented as confirmatory. Report with this caveat in
# the Supplementary Material (Anderson & Walsh 2013, Ecology).
pairwise_diet <- pairwise.adonis(x = LULC_sqrt, factors = data_raw_glm$DIET,
                                 sim.method = 'bray')
write.csv(pairwise_diet,
          file.path(output_path, "PERMANOVA_Bray_Pairwise_Diet.csv"),
          row.names = FALSE)

pairwise_loc <- pairwise.adonis(x = LULC_sqrt, factors = data_raw_glm$LOCOMOTION,
                                sim.method = 'bray')
write.csv(pairwise_loc,
          file.path(output_path, "PERMANOVA_Bray_Pairwise_Locomotion.csv"),
          row.names = FALSE)

message("   Pairwise PERMANOVA tables exported (Genus, Species, Diet, Locomotion).")

# ==============================================================================
# 5. UNIVARIATE ANALYSIS (GLMM + GLM model selection)
# ==============================================================================
message("\n[Analysis] Generalized Linear Mixed Models (GLMMs)...")

target_genera <- c("Puma", "Alouatta", "Mazama", "Brachyteles",
                   "Tayassu", "Myrmecophaga", "Leopardus", "Bradypus")
results_genus <- list(); plots_genus <- list(); plot_index <- 1

for (gen in target_genera) {
  res <- run_model_selection(gen, "GENUS", data_z)
  if (!is.null(res)) {
    results_genus[[gen]] <- res
    # Get color from colors_genus palette (centralized definition)
    cor_spec <- colors_genus[gen]
    if (is.na(cor_spec)) cor_spec <- "black"
    show_y <- (plot_index %% 2) != 0
    p <- plot_response_curves(res, gen, data_raw_glm,
                              use_log_y = TRUE, line_color = cor_spec,
                              show_y_label = show_y)
    if (!is.null(p)) { plots_genus[[gen]] <- p; plot_index <- plot_index + 1 }
  }
}
if (length(plots_genus) > 0) {
  panel_genus <- wrap_plots(plots_genus, ncol = 2) + plot_annotation(tag_levels = 'A')
  save_publication_plot(panel_genus, "Figure3_Bray_Panel_GLM_Genera.tiff",
                        width_mm = 174, height_mm = 250)
}

# Diet with standardized colors
# NOTE: The data contain two additional diet categories not included in GLMM
# modelling: "Fo" (Folivore, n = 5) and "Myr" (Myrmecophagous, n = 4).
# "Myr" is excluded because n < 5 (minimum required for Gamma GLMM stability).
# "Fo" is excluded because the single species assigned to it (Bradypus) is
# already modelled under Genus; merging it into "Fr/Fo" is ecologically
# unjustified. Both exclusions must be stated explicitly in the Methods.
# The global PERMANOVA (Section 4) retains all six categories as intended,
# since PERMANOVA does not require per-group sample-size thresholds.
target_diet <- c("Fr/On", "Hb/Fr", "Ca", "Fr/Fo")
results_diet <- list(); plots_diet <- list(); plot_index <- 1

for (diet in target_diet) {
  res <- run_model_selection(diet, "DIET", data_z)
  if (!is.null(res)) {
    results_diet[[diet]] <- res
    # Get color from colors_diet palette (centralized definition)
    cor_spec <- colors_diet[diet]
    if (is.na(cor_spec)) cor_spec <- "black"
    show_y <- (plot_index %% 2) != 0
    p <- plot_response_curves(res, diet, data_raw_glm,
                              use_log_y = TRUE, line_color = cor_spec,
                              show_y_label = show_y)
    if (!is.null(p)) { plots_diet[[diet]] <- p; plot_index <- plot_index + 1 }
  }
}
if (length(plots_diet) > 0) {
  panel_diet <- wrap_plots(plots_diet, ncol = 2) + plot_annotation(tag_levels = 'A')
  save_publication_plot(panel_diet, "Figure4_Bray_Panel_GLM_Diet.tiff",
                        width_mm = 174, height_mm = 180)
}

# Locomotion with standardized colors
target_loc <- c("Ar", "Sc", "Te")
results_loc <- list(); plots_loc <- list(); plot_index <- 1

loco_mapping <- c("Ar" = "Arboreal", "Sc" = "Scansorial", "Te" = "Terrestrial")

for (loc in target_loc) {
  res <- run_model_selection(loc, "LOCOMOTION", data_z)
  if (!is.null(res)) {
    results_loc[[loc]] <- res
    # Get color from colors_locomotion palette using full name
    loco_name <- loco_mapping[loc]
    cor_loc <- colors_locomotion[loco_name]
    if (is.na(cor_loc)) cor_loc <- "black"
    show_y <- (plot_index %% 2) != 0
    p <- plot_response_curves(res, loc, data_raw_glm,
                              use_log_y = TRUE, line_color = cor_loc,
                              show_y_label = show_y)
    if (!is.null(p)) { plots_loc[[loc]] <- p; plot_index <- plot_index + 1 }
  }
}
if (length(plots_loc) > 0) {
  panel_loc <- wrap_plots(plots_loc, ncol = 2) + plot_annotation(tag_levels = 'A')
  save_publication_plot(panel_loc, "Figure5_Bray_Panel_GLM_Locomotion.tiff",
                        width_mm = 174, height_mm = 130)
}

# ==============================================================================
# 5.1 EXPORT OF COMPETITIVE MODELS (delta AICc < 2)
# ==============================================================================
message("\n[Export] Supplementary table of competitive models...")

build_competitive_table <- function(results_list, group_name) {
  out <- list()
  for (taxon in names(results_list)) {
    dredge_table <- results_list[[taxon]]$table
    if (is.null(dredge_table)) next
    
    competitive <- as.data.frame(subset(dredge_table, delta < 2))
    if (nrow(competitive) == 0) next
    
    metric_cols <- c("df", "logLik", "AICc", "delta", "weight")
    var_cols    <- setdiff(names(competitive), metric_cols)
    
    formulas <- vapply(seq_len(nrow(competitive)), function(i) {
      vars_present <- var_cols[!is.na(competitive[i, var_cols])]
      vars_present <- vars_present[vars_present != "(Intercept)"]
      if (length(vars_present) == 0) "~ Null Model ~" else paste(vars_present, collapse = " + ")
    }, character(1))
    
    out[[taxon]] <- data.frame(
      Group              = group_name,
      Taxon              = taxon,
      Rank               = seq_len(nrow(competitive)),
      Selected_Variables = formulas,
      df                 = competitive$df,
      LogLik             = round(competitive$logLik, 3),
      AICc               = round(competitive$AICc, 3),
      Delta_AICc         = round(competitive$delta, 3),
      Akaike_Weight      = round(competitive$weight, 3)
    )
  }
  bind_rows(out)
}

competitive_full <- bind_rows(
  build_competitive_table(results_genus, "Genus"),
  build_competitive_table(results_diet,  "Diet"),
  build_competitive_table(results_loc,   "Locomotion")
)
write.csv(competitive_full,
          file.path(output_path, "Table_S_Competitive_Models_Full.csv"),
          row.names = FALSE)

# Backwards-compatible Top-3 table (kept for legacy reference)
top3_list <- list()
for (gen in names(results_genus)) {
  dt <- results_genus[[gen]]$table
  if (is.null(dt)) next
  top3 <- as.data.frame(head(dt, 3))
  metric_cols <- c("df", "logLik", "AICc", "delta", "weight")
  var_cols    <- setdiff(names(top3), metric_cols)
  formulas <- vapply(seq_len(nrow(top3)), function(i) {
    vars_present <- var_cols[!is.na(top3[i, var_cols])]
    vars_present <- vars_present[vars_present != "(Intercept)"]
    if (length(vars_present) == 0) "~ Null Model ~" else paste(vars_present, collapse = " + ")
  }, character(1))
  top3_list[[gen]] <- data.frame(Taxon = gen, Rank = seq_len(nrow(top3)),
                                 Delta_AICc = round(top3$delta, 3),
                                 Weight = round(top3$weight, 3),
                                 df = top3$df,
                                 LogLik = round(top3$logLik, 3),
                                 Selected_Variables = formulas)
}
write.csv(bind_rows(top3_list),
          file.path(output_path, "Table_S_Top3_Models_AICc.csv"),
          row.names = FALSE)

# ==============================================================================
# 6. RESIDUAL DIAGNOSTICS (DHARMa)
# ==============================================================================
message("\n[Diagnostics] DHARMa residual diagnostics...")

dharma_diagnostics <- function(model_list, targets, category_name,
                               n_sim = 1000, seed = GLOBAL_SEED) {
  out <- list()
  for (target_name in targets) {
    model_obj <- model_list[[target_name]]
    if (is.null(model_obj)) next
    
    model <- model_obj$model
    if (inherits(model, "averaging")) {
      model <- get.models(model_obj$table, subset = 1)[[1]]
    }
    
    set.seed(seed)
    sim <- simulateResiduals(fittedModel = model, n = n_sim, seed = seed)
    dispersion_test <- testDispersion(sim, plot = FALSE)
    uniformity_test <- testUniformity(sim, plot = FALSE)
    outlier_test    <- testOutliers(sim, plot = FALSE)
    
    out[[target_name]] <- data.frame(
      Category = category_name,
      Taxon = target_name,
      n_obs = model_obj$n,
      Dispersion_p = round(dispersion_test$p.value, 4),
      Uniformity_p = round(uniformity_test$p.value, 4),
      Outliers_p   = round(outlier_test$p.value, 4),
      Overall_Diagnostic = ifelse(
        dispersion_test$p.value > 0.05 & uniformity_test$p.value > 0.05 & outlier_test$p.value > 0.05,
        "OK", "WARNING"
      )
    )
  }
  bind_rows(out)
}

dharma_genus <- dharma_diagnostics(results_genus, names(results_genus), "Genus")
dharma_diet  <- dharma_diagnostics(results_diet, names(results_diet), "Diet")
dharma_loc   <- dharma_diagnostics(results_loc, names(results_loc), "Locomotion")

dharma_full <- bind_rows(dharma_genus, dharma_diet, dharma_loc)
write.csv(dharma_full,
          file.path(output_path, "Table_S_DHARMa_Diagnostics.csv"),
          row.names = FALSE)
message("   DHARMa diagnostics table exported.")

# ==============================================================================
# 7. MULTIMODEL INFERENCE & VARIABLE IMPORTANCE (Akaike weights)
# ==============================================================================
message("\n[Analysis] Relative variable importance (Akaike weights)...")

imp_genus <- extract_variable_importance(results_genus, "Genus")
imp_diet  <- extract_variable_importance(results_diet,  "Diet")
imp_loc   <- extract_variable_importance(results_loc,   "Locomotion")

df_importance <- bind_rows(imp_genus, imp_diet, imp_loc)

nice_names_imp <- c("PLAND_Forest"        = "PLAND (%)",
                    "NP_Forest"           = "NP",
                    "PD_Forest"           = "PD",
                    "PROX_MN_Forest"      = "PROX",
                    "Mean_ENN_Forest_m"   = "ENN (m)",
                    "Mean_Elevation_m"    = "Elevation (m)",
                    "Mean_Pop_Density"    = "Pop. Density",
                    "Mean_AREA_Forest_ha" = "AREA (ha)",
                    "Mean_FRAC_Forest"    = "FRAC",
                    "ED_Forest"           = "ED")

df_importance$Variable <- dplyr::recode(df_importance$Variable, !!!nice_names_imp)
write.csv(df_importance,
          file.path(output_path, "Table_S_Bray_Variable_Importance_Akaike.csv"),
          row.names = FALSE)

df_importance$Group <- factor(df_importance$Group,
                              levels = c("Genus", "Diet", "Locomotion"))

plot_importance <- ggplot(df_importance,
                          aes(x = Taxon, y = Variable, fill = Importance)) +
  geom_tile(color = "white", linewidth = 0.5) +
  geom_text(aes(label = Direction, color = Importance > 0.4),
            size = 6, fontface = "bold", show.legend = FALSE) +
  scale_color_manual(values = c("grey30", "white")) +
  scale_fill_viridis_c(limits = c(0, 1), option = "mako", direction = -1,
                       name = "Akaike\nWeight", labels = scales::percent) +
  facet_grid(~ Group, scales = "free_x", space = "free_x") +
  labs(x = NULL, y = NULL,
       title = "Relative Importance and Direction of Landscape Predictors") +
  theme_classic(base_size = 10, base_family = "sans") +
  theme(axis.text.x       = element_text(angle = 45, hjust = 1, face = "italic"),
        axis.text.y       = element_text(size = 9, face = "bold"),
        strip.background  = element_rect(fill = "grey90", color = "white"),
        strip.text        = element_text(face = "bold", size = 8.5),
        plot.title        = element_text(face = "bold", size = 11, hjust = 0.5),
        legend.position   = "right")

save_publication_plot(plot_importance,
                      "Figure6_Bray_Heatmap_Variable_Importance.tiff",
                      width_mm = 174, height_mm = 130)

# ==============================================================================
# 8. EFFECTIVE HABITAT AREA (EHA) VARIATION - WITH STANDARDIZED COLOR PALETTES
# ==============================================================================
message("\n[Export] EHA variation summaries...")

# Forest-cover (PLAND) variation across species' EHAs
variation_pland_species <- data_raw_glm %>%
  group_by(SPECIES) %>%
  summarise(PLAND_Min  = min(PLAND_Forest, na.rm = TRUE),
            PLAND_Max  = max(PLAND_Forest, na.rm = TRUE),
            PLAND_Mean = mean(PLAND_Forest, na.rm = TRUE),
            .groups = "drop")
write.csv(variation_pland_species,
          file.path(output_path, "Table_S_Habitat_Amount_Variation.csv"),
          row.names = FALSE)

# EHA size variation across species (additional descriptive statistic)
variation_eha_species <- data_raw_glm %>%
  group_by(SPECIES) %>%
  summarise(EHA_Min    = min(EHA_ha, na.rm = TRUE),
            EHA_Max    = max(EHA_ha, na.rm = TRUE),
            EHA_Mean   = mean(EHA_ha, na.rm = TRUE),
            EHA_Median = median(EHA_ha, na.rm = TRUE),
            n_SU       = n(),
            .groups = "drop")
write.csv(variation_eha_species,
          file.path(output_path, "Table_S_EHA_Size_Variation.csv"),
          row.names = FALSE)

# Prepare data for visualization (order species by median PLAND)
data_boxplot <- data_raw_glm %>%
  mutate(SPECIES = fct_reorder(SPECIES, PLAND_Forest, .fun = median, .desc = FALSE))

# =============================================================================
# FIGURE 8: EHA Variation by Species (PLAND) - GRAY MONOCHROME
# =============================================================================
plot_pland_species <- ggplot(data_boxplot,
                              aes(x = SPECIES, y = PLAND_Forest)) +
  geom_boxplot(alpha = 0.75, fill = "gray70", color = "black", 
               outlier.shape = 21, outlier.fill = "gray40", 
               outlier.size = 2.5, outlier.alpha = 0.6) +
  scale_y_continuous(labels = label_percent(scale = 1), limits = c(0, 100),
                     breaks = seq(0, 100, by = 20)) +
  labs(x = "Species", 
       y = "Forest Cover within EHA (%)",
       title = "Habitat Amount Variation Across Species (PLAND)") +
  theme_classic(base_size = 11, base_family = "sans") +
  theme(plot.title       = element_text(face = "bold", size = 13, hjust = 0.5, 
                                         margin = margin(b = 10)),
        axis.text.x      = element_text(angle = 45, hjust = 1, face = "italic", 
                                         size = 10),
        axis.text.y      = element_text(size = 10),
        axis.title       = element_text(face = "bold", size = 11),
        panel.grid.major.y = element_line(color = "lightgray", linewidth = 0.3),
        legend.position  = "none",
        plot.margin      = margin(t = 10, r = 10, b = 10, l = 10))

save_publication_plot(plot_pland_species,
                      "Figure_08_EHA_Variation_By_Species_PLAND.tiff",
                      width_mm = 174, height_mm = 130)

message("   Figure 8 (Species by PLAND) exported.")

# =============================================================================
# FIGURE 9: EHA Variation by Locomotion Type - STANDARDIZED COLORS
# =============================================================================
data_boxplot_loco <- data_raw_glm %>%
  mutate(
    # Translate short locomotion codes to full names to match colors_locomotion
    LOCOMOTION = dplyr::recode(LOCOMOTION, !!!loco_mapping),
    LOCOMOTION = fct_relevel(LOCOMOTION, "Arboreal", "Scansorial", "Terrestrial"),
    SPECIES    = fct_reorder(SPECIES, PLAND_Forest, .fun = median, .desc = FALSE)
  )

plot_pland_locomotion <- ggplot(data_boxplot_loco,
                                 aes(x = SPECIES, y = PLAND_Forest, fill = LOCOMOTION)) +
  geom_boxplot(alpha = 0.8, color = "black", outlier.shape = 21,
               outlier.size = 2.5, outlier.alpha = 0.6) +
  scale_fill_manual(values = colors_locomotion,
                    name = "Locomotion Type",
                    labels = c("Arboreal", "Scansorial", "Terrestrial")) +
  scale_y_continuous(labels = label_percent(scale = 1), limits = c(0, 100),
                     breaks = seq(0, 100, by = 20)) +
  labs(x = "Species", 
       y = "Forest Cover within EHA (%)",
       title = "Habitat Amount Variation Across Species by Locomotion Type") +
  theme_classic(base_size = 11, base_family = "sans") +
  theme(plot.title       = element_text(face = "bold", size = 13, hjust = 0.5,
                                         margin = margin(b = 10)),
        axis.text.x      = element_text(angle = 45, hjust = 1, face = "italic",
                                         size = 10),
        axis.text.y      = element_text(size = 10),
        axis.title       = element_text(face = "bold", size = 11),
        panel.grid.major.y = element_line(color = "lightgray", linewidth = 0.3),
        legend.position  = "bottom",
        legend.title     = element_text(face = "bold", size = 10),
        legend.text      = element_text(size = 10),
        legend.margin    = margin(t = 10),
        plot.margin      = margin(t = 10, r = 10, b = 10, l = 10))

save_publication_plot(plot_pland_locomotion,
                      "Figure_09_EHA_Variation_By_Locomotion.tiff",
                      width_mm = 174, height_mm = 140)

message("   Figure 9 (Locomotion type) exported.")

# =============================================================================
# FIGURE 10: EHA Variation by Diet Type - STANDARDIZED COLORS
# =============================================================================
data_boxplot_diet <- data_raw_glm %>%
  mutate(DIET = fct_relevel(DIET, "Ca", "Fr/Fo", "Hb/Fr", "Fr/On")) %>%
  mutate(SPECIES = fct_reorder(SPECIES, PLAND_Forest, .fun = median, .desc = FALSE))

plot_pland_diet <- ggplot(data_boxplot_diet,
                           aes(x = SPECIES, y = PLAND_Forest, fill = DIET)) +
  geom_boxplot(alpha = 0.8, color = "black", outlier.shape = 21,
               outlier.size = 2.5, outlier.alpha = 0.6) +
  scale_fill_manual(values = colors_diet,
                    name = "Diet Type",
                    labels = diet_labels_dict) +
  scale_y_continuous(labels = label_percent(scale = 1), limits = c(0, 100),
                     breaks = seq(0, 100, by = 20)) +
  labs(x = "Species",
       y = "Forest Cover within EHA (%)",
       title = "Habitat Amount Variation Across Species by Diet Type") +
  theme_classic(base_size = 11, base_family = "sans") +
  theme(plot.title       = element_text(face = "bold", size = 13, hjust = 0.5,
                                         margin = margin(b = 10)),
        axis.text.x      = element_text(angle = 45, hjust = 1, face = "italic",
                                         size = 10),
        axis.text.y      = element_text(size = 10),
        axis.title       = element_text(face = "bold", size = 11),
        panel.grid.major.y = element_line(color = "lightgray", linewidth = 0.3),
        legend.position  = "bottom",
        legend.title     = element_text(face = "bold", size = 10),
        legend.text      = element_text(size = 10),
        legend.margin    = margin(t = 10),
        plot.margin      = margin(t = 10, r = 10, b = 10, l = 10))

save_publication_plot(plot_pland_diet,
                      "Figure_10_EHA_Variation_By_Diet.tiff",
                      width_mm = 174, height_mm = 140)

message("   Figure 10 (Diet type) exported.")

message("\n[Complete] All analyses finished successfully.")
message("\nOutput files generated:")
message("  - Collinearity_Correlation_GLM.png")
message("  - Correlation_Composition_NMDS.png")
message("  - Figure2_Bray_NMDS_Genus_Final.tiff (REVISED with standardized colors)")
message("  - Figure3_Bray_Panel_GLM_Genera.tiff (REVISED with standardized colors)")
message("  - Figure4_Bray_Panel_GLM_Diet.tiff (REVISED with standardized colors)")
message("  - Figure5_Bray_Panel_GLM_Locomotion.tiff (REVISED with standardized colors)")
message("  - Figure6_Bray_Heatmap_Variable_Importance.tiff")
message("  - Figure_08_EHA_Variation_By_Species_PLAND.tiff (monochrome)")
message("  - Figure_09_EHA_Variation_By_Locomotion.tiff (standardized colors)")
message("  - Figure_10_EHA_Variation_By_Diet.tiff (standardized colors)")
message("  - Table_S_Collinearity_VIF.csv")
message("  - Envfit_Configuration_Bray_Results.csv")
message("  - Table_S_Betadisper_Bray_Results.csv")
message("  - Table_S_PERMANOVA_Global_Bray.csv")
message("  - PERMANOVA_Bray_Pairwise_Genus.csv")
message("  - PERMANOVA_Bray_Pairwise_Species.csv")
message("  - PERMANOVA_Bray_Pairwise_Diet.csv")
message("  - PERMANOVA_Bray_Pairwise_Locomotion.csv")
message("  - Table_S_Competitive_Models_Full.csv")
message("  - Table_S_Top3_Models_AICc.csv")
message("  - Table_S_DHARMa_Diagnostics.csv")
message("  - Table_S_Bray_Variable_Importance_Akaike.csv")
message("  - Table_S_Habitat_Amount_Variation.csv")
message("  - Table_S_EHA_Size_Variation.csv")

# ==============================================================================
# 9. SESSION INFO
# ==============================================================================
message("\n[Session] Package versions and system information:")
sessionInfo()
